import React, { useMemo } from 'react';
import type { SpotifyTrack } from '../services/SpotifyService';
import './Receipt.css';

interface ReceiptProps {
  user: { display_name?: string } | null;
  tracks: SpotifyTrack[];
  timeRange: 'short_term' | 'medium_term' | 'long_term';
}

const dateStr = () => new Date().toLocaleString();

const friendlyRange: Record<ReceiptProps['timeRange'], string> = {
  short_term: 'Last 4 Weeks',
  medium_term: 'Last 6 Months',
  long_term: 'All Time'
};

const fontClasses = ['f1','f2','f3','f4'];

const Receipt: React.FC<ReceiptProps> = ({ user, tracks, timeRange }) => {
  const items = useMemo(() => tracks.map((t, i) => ({
    i: (i+1).toString().padStart(2,'0'),
    name: t.name,
    artist: t.artists.map(a=>a.name).join(', '),
    url: t.external_urls?.spotify
  })), [tracks]);
  return (
    <div className="receipt-wrapper">
      <div className="paper">
        <div className="r-head">
          <h3 className="store f1">ROTIFY RECEIPT</h3>
          <div className="meta f2">User: {user?.display_name || 'Anon'} | {friendlyRange[timeRange]}</div>
          <div className="meta f3">{dateStr()}</div>
        </div>
        <div className="r-body">
          {items.map((it, idx) => (
            <div className={`line ${fontClasses[idx % fontClasses.length]}`} key={idx}>
              <span className="idx">{it.i}</span>
              {it.url ? <a href={it.url} target="_blank" rel="noreferrer" className="t">{it.name}</a> : <span className="t">{it.name}</span>}
              <span className="artist">{it.artist}</span>
            </div>
          ))}
        </div>
        <div className="r-foot f4">
          <div>THANK YOU FOR LISTENING ♫</div>
          <div className="barcode" aria-hidden>
            <span></span><span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span><span></span>
          </div>
          <div className="foot-note">Generated by Rotify</div>
        </div>
      </div>
    </div>
  );
};

export default Receipt;
