import React from 'react';
import type { SpotifyTrack, SpotifyArtist, SpotifyPlaylist } from '../services/SpotifyService';
import { formatDuration } from '../services/SpotifyService';
import './Receipt.css';

interface ReceiptProps {
  user: { display_name?: string } | null;
  timeRange: 'short_term' | 'medium_term' | 'long_term';
  sections: {
    recent: SpotifyTrack[];
    topTracks: SpotifyTrack[];
    topArtists: SpotifyArtist[];
    playlists: SpotifyPlaylist[];
  };
  selectedFont: string;
  canvas?: string;
}

const dateStr = () => new Date().toLocaleString();

const friendlyRange: Record<ReceiptProps['timeRange'], string> = {
  short_term: 'Last 4 Weeks',
  medium_term: 'Last 6 Months',
  long_term: 'All Time'
};

const Receipt: React.FC<ReceiptProps> = ({ user, timeRange, sections, selectedFont, canvas }) => {
  const recent = sections.recent.slice(0,10);
  const topT = sections.topTracks.slice(0,10);
  const topA = sections.topArtists.slice(0,10);
  const pls = sections.playlists.slice(0,10);
  
  const mapTrack = (t: SpotifyTrack, i:number) => ({
    idx: (i+1).toString().padStart(2,'0'),
    name: t.name,
    sub: t.artists.map(a=>a.name).join(', '),
    duration: formatDuration(t.duration_ms),
    url: t.external_urls?.spotify
  });
  
  const mapArtist = (a: SpotifyArtist, i: number) => ({
    idx: (i+1).toString().padStart(2,'0'),
    name: a.name,
    sub: `${a.genres?.slice(0, 2).join(', ') || 'Various'} | ♫${a.popularity || 0}`,
    url: a.external_urls?.spotify
  });
  
  const mapPlaylist = (p: SpotifyPlaylist, i: number) => ({
    idx: (i+1).toString().padStart(2,'0'),
    name: p.name,
    sub: `${p.tracks?.total || 0} tracks`,
    url: p.external_urls?.spotify
  });

  // decide background style; allow 'none' to disable image
  const bgStyle: React.CSSProperties = { fontFamily: selectedFont };
  if (canvas && canvas !== 'none') {
    // use runtime-resolved path as-is (e.g., '/paper.png')
    bgStyle.background = `url(${canvas}) center/cover no-repeat, var(--paper-bg, #fff)`;
  } else {
  // if none, explicitly remove background image and use paper bg color
  bgStyle.backgroundImage = 'none';
  bgStyle.backgroundColor = 'var(--paper-bg, transparent)';
  }

  return (
    <div className="receipt-wrapper">
      <div className="paper" style={bgStyle}>
        <div className="r-head">
          <h3 className="store f1">ROTIFY RECEIPT</h3>
          <div className="meta f2">User: {user?.display_name || 'Anon'} | {friendlyRange[timeRange]}</div>
          <div className="meta f3">{dateStr()}</div>
        </div>
        <div className="r-body">
          {recent.length > 0 && <Section title="RECENT" items={recent.map(mapTrack)} />}
          {topT.length > 0 && <Section title="TOP TRACKS" items={topT.map(mapTrack)} />}
          {topA.length > 0 && <Section title="TOP ARTISTS" items={topA.map(mapArtist)} />}
          {pls.length > 0 && <Section title="PLAYLISTS" items={pls.map(mapPlaylist)} />}
        </div>
        <div className="r-foot f4">
          <div>THANK YOU FOR LISTENING ♫</div>
          <div className="barcode" aria-hidden>
            <span></span><span></span><span></span><span></span><span></span><span></span>
            <span></span><span></span><span></span><span></span><span></span><span></span>
          </div>
          <div className="foot-note">Generated by Rotify</div>
        </div>
      </div>
    </div>
  );
};

interface SectionItem { idx: string; name: string; sub: string; duration?: string; url?: string }
const Section: React.FC<{ title: string; items: SectionItem[] }> = ({ title, items }) => (
  <div className="receipt-section">
    <div className="sec-title f5">-- {title} --</div>
    {items.map((it, idx) => (
      <div className="line" key={idx}>
        <span className="idx">{it.idx}</span>
        {it.url ? <a href={it.url} target="_blank" rel="noreferrer" className="t">{it.name}</a> : <span className="t">{it.name}</span>}
        {it.sub && <span className="artist">{it.sub}</span>}
        {it.duration && <span className="duration">{it.duration}</span>}
      </div>
    ))}
  </div>
);

export default Receipt;
